var t = {
    service_not_available: 'Service ist not available',
    login: 'Login',
    more: 'More',
    none: 'No',
    search: 'Search',
    results: 'results',
    for: 'for',
    rechnungsnummer: 'Invoice number',
    yes: 'Yes',
    no: 'No',
    quantity: 'Quantity',
    date: 'Date',
    articles: 'Article',
    rechnung: 'Invoice',
    status: 'Status',
    document: 'Document',
    show: 'Show',
    download: 'download',
    confirm: 'Confirm',
    confirmation: 'Confirmation',
    will: 'will',
    by: 'by',
    sent: 'sent',
    the: 'The',
    address: 'Address',
    save: 'save',
    address_save: 'Save address',
    password: 'Password',
    username: 'Username',
    or: 'or',
    is: 'is',
    wrong: 'wrong',
    password_wrong: 'Password is wrong!',
    password_or_username_wrong: 'Username or Password is wrong!',
    address_change_confirmation: 'Please insert your password for confirmation!',
    letters: 'letters',
    minimun: 'minimum',
    confirmation_sent_email: 'The Confirmation will be sent by Email!',
    show_articles: 'Show items',
    show_invoices: 'Show invoices'
};